### ISSUE TITLE
Shopping List Error

### ISSUE THREAD

**Issue by robertkub** [freeCodeCamp/freeCodeCamp#10570]
Challenge [shopping-list](https://www.freecodecamp.com/en/challenges/basic-javascript/shopping-list) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

``` js


var myList = [["Noodles", 20],["Almond Milk", 1],["Crackers", 15],["Kale", 2],["Rice", 1]];


```

It will not show that this is complete? There seem to be no errors with my input.

**Comment by ngratton** [comment]
Same here.

`var myList = [
  ["Meat", 2],
  ["Milk", 64],
  ["Bananas", 8],
  ["Cookies", 34],
  ["Beans", 234]
];`

On the first test succeeds.

>  "myList should be an array"

**Comment by dhcodes** [comment]
@robertkub @ngratton What browsers are you using? I used both of your code snippets in Chrome and Firefox and was able to pass all the tests. Could you try copying your code to the clipboard and refreshing the page, and then pasting it back in?

**Comment by ngratton** [comment]
@dhcodes I use Chrome 52.0.2743.116. 
I also tried to complete the challenge in a freshly opened Safari 9.1.3 and newly installed Firefox 48.0.2, by copying/pasting the code, still with no success. I also retyped the whole thing with different values, twice; still not working. It won't even recognize myList as an array.

**Comment by Axfinity** [comment]
var myList = [['Hard disk',50],['keyboard',5],['headphone',20],['router',25],['vr',600]];
I see no reason why this should not be working.But this is not working

**Comment by robertkub** [comment]
I have tried that, I'm currently using the most updated version of safari!

**Comment by dhcodes** [comment]
I don't seem to be able to duplicate this. @FreeCodeCamp/issue-moderators can anyone else break this?

**Comment by hallaathrad** [comment]
Cannot replicate on any browser (Chrome, Safari and Firefox. MacOS Sierra).

**Comment by Gslaughl** [comment]
For what it's worth, I'm having the same issue:
`var myList = [["shoes", 2], ["eggs", 12], ["pigs", 2], ["breads", 13], ["dragonballs", 9001]];`
I tried refreshing and copy-pasting and stuff, but only the first test will pass.

**Comment by GrahamAW** [comment]
I'm having the same issue. I tried my input copied and pasted some from above.

MacOSX - Chrome - Version 52.0.2743.116 (64-bit)

**Comment by ngratton** [comment]
Managed to have it confirm, just once, by copying-pasting the whole snippet, on another computer using Chrome 53 on Windows 10. 

However, I am unable to reproduce this **success** on neither systems.

**Comment by cloudrainsnow** [comment]
I have the same issue. User agent is: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by northless** [comment]
Same here, this list wold not pass: var myList = [["fruta", 10], ["pudim", 10], ["arroz", 2], ["laranjas", 98], ["gummy bears", 100], ["peanuts", 9001]];
Updated to the latest Chrome version and the issue was solved, now it works. Check if you guys are running the last version, if not, update and try again 🚨

**Comment by marhyorh** [comment]
@dhcodes @hallaathrad Do old browsers support `forEach` ??

**Comment by hallaathrad** [comment]
forEach is ES5, so it should be supported fairly well... except for ie<9 (as usual)

**Comment by marhyorh** [comment]
Then that challenge should have no problem if not on ie8 and below

**Comment by karuppiah7890** [comment]
@robertkub Hey! The issue still exists ? And when you tried long ago, all test cases failed huh ?

**Comment by systimotic** [comment]
Any chance we could get an update on this? I can not reproduce this either. Looking at @northless' comment, could this have been a browser issue?

**Comment by cvorak** [comment]
> var myList = [["Snickers", 5], ["Gummy bears", 3], ["Plants", 5]]; 

   not passing on the latest version of Chrome.

**Comment by systimotic** [comment]
@cvorak Remember that you need at least 5 items in your array. If you put 5 items in there, does it work for you?

**Comment by cvorak** [comment]
It works with 5 items, issue never was here. Sorry for wasting your time.

**Comment by systimotic** [comment]
@cvorak No worries! Next time, please try the "Help" button first.

I'm closing this issue as it appears to have been an issue with a version of Chrome. Please reopen if it resurfaces. 👍

**Comment by gulptech** [comment]
Same problem as other tests.  Fails, refresh, then pass.
