### ISSUE TITLE
Waypoint 'Use the Bootstrap Grid to Put Elements Side By Side'

### ISSUE THREAD

**Issue by sidneygijzen** [FreeCodeCamp/freecodecamp#1147]
I'm working through the Bootstrap section at the moment and at the exercise 'Use the Bootstrap Grid to Put Elements Side By Side' I encountered the following:

1. When I start the exercise, I already accomplished a sub-goal of 'Your buttons should all be wrapped within the same div element with the class "row".' without doing anything.  See the first screenshot below.
2. As soon as I start to add in the div with the class 'row', the exercise validates itself, i.e. the button 'Go to my next challenge' becomes active. See the second screenshot below.

Screenshot belonging to point 1
![fcc_waypoint_bootstrap_grid_start](https://cloud.githubusercontent.com/assets/6213045/8397467/36593b8c-1dcc-11e5-8982-856da9ad05b5.png)

Screenshot belonging to point 2
![fcc_waypoint_bootstrap_grid_validates](https://cloud.githubusercontent.com/assets/6213045/8397473/3ed13c92-1dcc-11e5-9d28-2031d5f55f01.png)

**Comment by QuincyLarson** [comment]
Thank you for your help! We've now fixed this in production!

**Comment by sidneygijzen** [comment]
You're welcome. Thanks for the fast fix!

**Comment by Ekbaazigar** [comment]
<div class='cols-xs-4'>
    <button class='btn btn-block btn-primary'>Like</button>
  </div>
  <div class='cols-xs-4'>
    <button class='btn btn-block btn-info'>Info</button>
  </div>
  <div class='cols-xs-4'>
    <button class='btn btn-block btn-danger'>Delete</button>
  </div>
 </div>

its still complaining about "Each of your bootstrap buttons should be wrapped within its own div element class.......

**Comment by Ekbaazigar** [comment]
sorry here is the code snippet

"  <div class='cols-xs-4'>
    <button class='btn btn-block btn-primary'>Like</button>
  </div>
  <div class='cols-xs-4'>
    <button class='btn btn-block btn-info'>Info</button>
  </div>
  <div class='cols-xs-4'>
    <button class='btn btn-block btn-danger'>Delete</button>
  </div>
 </div>"

**Comment by Ekbaazigar** [comment]
![image](https://cloud.githubusercontent.com/assets/4277269/9104816/8e5b3cba-3bc5-11e5-9168-18a9dcb7f37e.png)

I am still getting the error for 

![image](https://cloud.githubusercontent.com/assets/4277269/9104822/a6f846e6-3bc5-11e5-8e07-b134580c1597.png)
