### ISSUE TITLE
Untranslated challenge links do not respect url lang

### ISSUE THREAD

**Issue by Bouncey** [FreeCodeCamp/FreeCodeCamp#11627]
Language specific routes not correct for new sessions after selecting a different language.

If I select a language, the routing is all correct for that session.

If I start a new session, translated challenges render correctly (they are translated), but lang routes revert to `en` after first navigation.

![anim](https://cloud.githubusercontent.com/assets/18572518/20229890/c8882314-a850-11e6-9696-a31e2d471bc5.gif)

PR #11545 relies on this issue being resolved

**Comment by BerkeleyTrue** [comment]
> Language specific routes not correct for new sessions after selecting a different language.

I cannot reproduce this. Language is preserved between sessions. Can you provide a gif of this?

This issue should focus only on the untranslated challenges in the map not respecting the language in the url

**Comment by Bouncey** [comment]
> I cannot reproduce this. Language is preserved between sessions. Can you
provide a gif of this?

In the opening comment of this issue.

**Comment by BerkeleyTrue** [comment]
> Language specific routes not correct for new sessions after selecting a different language.

What I see in the gif it that the untranslated challenge link does not respect the language in the url. Clicking on translated challenge links respects the url. This disqualifies an issue with sessions.

So is that line a separate issue or is this the only issue?

**Comment by Bouncey** [comment]
So in this one, I navigate to `localhost:3000` ans the uri lang is `es`, I navigate to a translated challenge and the uri lang reverts to `en`

![anim](https://cloud.githubusercontent.com/assets/18572518/20403355/8bacfeae-acf8-11e6-8a60-bf2191b477ce.gif)

**Comment by hmkt999** [comment]
Unsubscribe

**Comment by BerkeleyTrue** [comment]
@hmkt999 This is not a mailing list. You need to go into your github settings to stop receiving emails.

**Comment by hmkt999** [comment]
@BerkeleyTrue Ah ok. Thank you :)

**Comment by BerkeleyTrue** [comment]
@Bouncey I'm not sure what is going on but I cannot replicate this locally.

**Comment by BerkeleyTrue** [comment]
This is on your lang translation note PR.
![lang-issue-test](https://cloud.githubusercontent.com/assets/6775919/20692183/15f29624-b58b-11e6-9586-5ee250f2a4b4.gif)

**Comment by raisedadead** [comment]
@BerkeleyTrue it's reproducible on the staging as seen in the OP for this issue. And @Bouncey's PR results in the same as your GIF.

**Comment by raisedadead** [comment]
However in both cases, if I delete the cookies from the browser (creating a true fresh session). And login again. The language remains `en` even though on the settings page I can see it to be `es`

**Comment by BerkeleyTrue** [comment]
> And @Bouncey's PR results in the same as your GIF.

So it is fixed?

**Comment by raisedadead** [comment]
> So it is fixed?

Yes. The PR fixes the issue.

**Comment by BerkeleyTrue** [comment]
@raisedadead That PR has been merged. So staging should be fixed as well

**Comment by raisedadead** [comment]
Apologies I meant https://github.com/FreeCodeCamp/FreeCodeCamp/pull/11801 fixes it.

**Comment by BerkeleyTrue** [comment]
@raisedadead The Gif I supplied is not from that PR. So I am having a different experience than you and @Bouncey

**Comment by raisedadead** [comment]
@BerkeleyTrue so you merged a different PR that gave you the result in your gif? If yes, which one? I can revert locally and check?

**Comment by BerkeleyTrue** [comment]
#11545 does not replicate the issue. But I don't think it has anything to with the pr. I'm just not seeing this behavior.

**Comment by raisedadead** [comment]
@BerkeleyTrue you are correct. I just merged #11545 locally and `npm` installed. And I get the same behavior as you.

This issue is not reproducible with #11545 merged.

**Comment by Bouncey** [comment]
So previous to this GIF, I checked out #11545 and did: 
`git pull --rebase upstream staging`
`rm -r node_modules`
`npm install`
`gulp`
![anim](https://cloud.githubusercontent.com/assets/18572518/20731375/0f9d825a-b682-11e6-900a-e00db8a237a3.gif)
I am still seeing the issue that #11801 fixes
