### ISSUE TITLE
On closing the map section, the lesson section isn't  resizable

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/freeCodeCamp#16300]
#### Issue Description
As you can see in the GIF below when the map section is not closed the lesson section gets resized easily. But when it is toggled-off the lesson section is not resizing to the left.
![](https://i.imgur.com/TX1m7AF.gif)

#### Browser Information

* Browser Name, Version:  Chrome (latest release) & Firefox (57.0.2).
* Operating System: Windows 10 Pro 32 bit.
* Mobile, Desktop, or Tablet: Desktop.

**Comment by QuincyLarson** [comment]
@vkWeb Nice find! Yes - we definitely need to fix this.

**Comment by abohannon** [comment]
I can take a crack at fixing this if nobody minds.

**Comment by meda123** [comment]
This would be a first-time contribution, so I'll take a look as well!

**Comment by vkWeb** [comment]
@abohannon You can start working on this issue. Please, go through our [Contributing guidelines](https://github.com/freeCodeCamp/freeCodeCamp/blob/staging/CONTRIBUTING.md).

@meda123 I'm extremely sorry but there are a lot of [outstanding issues](https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted) which needs attention. We'll be looking forward to your PR.

**Comment by vkWeb** [comment]
@QuincyLarson This issue is being addressed by @abohannon.

**Comment by QuincyLarson** [comment]
Hi @abohannon Have you had time to make any progress on this?

**Comment by abohannon** [comment]
Hey @QuincyLarson, took a look yesterday and plan to get back to it tomorrow (possibly tonight). Certainly a learning curve digesting the codebase for the first time. Is there anything I should know about how the panes and dividers are structured/work together? I think I've found the redux action that might be responsible, but will need to debug further. Thanks for the opportunity to troubleshoot this.

**Comment by sachinlamba** [comment]
I tried to check on this. Actually, 2 files we need to udpate, I think. 1. \freeCodeCamp\common\app\Panes\Panes.jsx  &   2. \freeCodeCamp\common\app\Panes\redux\index.jsx . Code is working like whole 100% browser width is divided into totalNoOfPanels. bcz of that, Side-panel(Ques description part panel) getting its min & max width(or left-right values) which is increased to approx 33% after Map-Panel hide. (First timer,so, dont want to change anything r8 now in this project.) Please tell if I am wrong.

**Comment by abohannon** [comment]
@sachinlamba thanks for the feedback. Your input and Redux dev tools helped me pinpoint what seems to be the problematic action, `dividerClicked`. Removing `dividerBuffer` from `leftBound` gets rid of the weird auto-resizing behavior and results in a semi-normal resizing effect, however the user still isn't able to collapse the `leftPane` all the way when the map pane is gone. If I get rid of both `leftBound` and `rightBound`, the user is able to resize normally, except the panes are able to resize beyond their neighbors, so not ideal.

Also, I'm not sure if this is intentional (maybe I'm not understanding the semantics for the pane state properties), but the `leftPane` and `rightPane` seem to be off by one index. In the attached screen shot, you'll see that map isn't visible, but it's logging as `leftPane`. Also, the `dividerLeft` for `rightPane` is 66.66 when one would assume it would be 0. Finally, when the map pane IS visible, `leftPane`
![screen shot 2017-12-31 at 1 01 32 pm](https://user-images.githubusercontent.com/889536/34464195-02e0f722-ee2b-11e7-8d63-2c056a4f8800.png)
![screen shot 2017-12-31 at 12 52 12 pm](https://user-images.githubusercontent.com/889536/34464196-02f9895e-ee2b-11e7-83b3-b9748df58a52.png)

 returns an empty object when you'd assume it should return map pane state.

I'll keep working on this.

**Comment by abohannon** [comment]
@vkWeb I think I'm ready to submit a PR for this. Having an issue with the tests, though. Getting a ton of what appear to be linting errors in files I didn't edit. There don't appear to be any errors in my files. Should I submit the PR regardless?

**Comment by QuincyLarson** [comment]
@abohannon can you pull the latest version of staging and merge it into your branch, then try running the `npm run lint` command?

**Comment by abohannon** [comment]
@QuincyLarson turns out I had a rogue eslint file conflicting. Deleted it and all tests passed. PR request submitted.

**Comment by vkWeb** [comment]
@abohannon Great job. 🤗

**Comment by vkWeb** [comment]
@QuincyLarson, @abohannon, @raisedadead. This issue has been fixed. [See comment on #16394](https://github.com/freeCodeCamp/freeCodeCamp/pull/16394#issuecomment-355724765).

**Comment by QuincyLarson** [comment]
@vkWeb Thanks for catching this, and for closing the issue :)

**Comment by vkWeb** [comment]
@QuincyLarson Always for freeCodeCamp. No thanks, Sir. :)
