### ISSUE TITLE
How to Use Passport Strategies & Create New Middleware 

### ISSUE THREAD

**Issue by clickingmouse** [freeCodeCamp/freeCodeCamp#16967]
https://learn.freecodecamp.org/information-security-and-quality-assurance/advanced-node-and-express/create-new-middleware/

1) code does not work for mongodb package 3.X needs 2.X or will get db.collection is not a function.  hence this dependency needs to be more strictly enforced
error...

2) test no.2 does not pass even though i am pretty certain code redirects to '/' 

#### Challenge Name

https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/create-new-middleware
https://beta.freecodecamp.org/en/challenges/advanced-node-and-express/how-to-use-passport-strategies
#### Browser Information

* Browser Name, Version: 
* Operating System: 
* Mobile, Desktop, or Tablet: 

#### Your Code

https://tan-bow.glitch.me/
```js



```

**Comment by QuincyLarson** [comment]
@Em-Ant Please take a look at this. What are your thoughts on this? Is this something that we should fix?

**Comment by Em-Ant** [comment]
@QuincyLarson we have CORS issue (probably for all the challenges) because https;//learn.freecodecamp.com is no included in the list of allowed domains. We should check all the projects, they have different strategies for handling CORS.

![istantanea_2018-06-03_20-07-05](https://user-images.githubusercontent.com/12955734/40889608-f151da7c-6769-11e8-861e-aa3e54ae63de.png)

**Comment by Em-Ant** [comment]
Create new middleware works, allowing the new domain

![istantanea_2018-06-03_20-28-12](https://user-images.githubusercontent.com/12955734/40889763-bc94cc2e-676c-11e8-8842-3a57e096deb8.png)

@clickingmouse  be aware that the redirection is tested searching for the text 'Home page' so you have to put it somewhere in the '/' page. Probably the test or the description could be improved.

**Comment by QuincyLarson** [comment]
@Em-Ant Awesome! Thanks! I'm closing this issue.

@clickingmouse Can you think of a way that we could improve the challenge description so that this is less ambiguous? If so, would you be interested in opening a pull request to improve the wording?

**Comment by raditotev** [comment]
This is still failing if there is no "Home page" content on the index page.

**Comment by mattszcz** [comment]
This is still an issue. Needs to be re-opened. 

Currently, the only way to pass this challenge is to search the FCC forum or issue tracker for this hidden solution.

**Comment by mdwattendorf** [comment]
Still broken for me.  I just put "Home Page" in the index.pug description.  Either add that to the challenge or just fix the glitch/github clone?

<img width="842" alt="screen shot 2018-09-14 at 7 09 43 pm" src="https://user-images.githubusercontent.com/27507807/45580758-1e4d1f80-b852-11e8-9aee-9b20c592915b.png">

**Comment by Em-Ant** [comment]
@mdwattendorf @mattszcz you are right. The test works checking that 'Home page' is in the pug template. I think we should update the challenge description specifying this requirement.

**Comment by BTmathic** [comment]
(I should add, this is my first time looking at the challenges/tests so I could be missing something obvious about why this can't be done, but it just looks like jQuery with the $.get() so I imagine this would work.)

**Comment by iasjem** [comment]
> Still broken for me. I just put "Home Page" in the index.pug description. Either add that to the challenge or just fix the glitch/github clone?
> 
> <img alt="screen shot 2018-09-14 at 7 09 43 pm" width="842" src="https://user-images.githubusercontent.com/27507807/45580758-1e4d1f80-b852-11e8-9aee-9b20c592915b.png">

I also experience the same issue for that part of Create New Middleware. This solution worked for me very well though. Code to add for `views/pug/index.pug`:

`meta(name='description', content='A cool thing made with HyperDev. This is also the Home page')`

**Comment by SkipHendriks** [comment]
I thought I'd go ahead and create a pull request for the clone. No clue if that would automatically propagate to the glitch version, but I do sure hope so. I changed the description to `meta(name='description', content='Home page')` Changing the test to check for an URL might be more future proof, but I highly doubt we will break the test in the future.

**Comment by kingdopamine** [comment]
Just wasted hours of my life on this challenge due to the omission of very simple information critical to passing this challenge. How can FCC not include something as simple as "change the title from 'Hello' to 'Home page' in the instructions. What a piss take. I'm furious.

**Comment by RandellDawson** [comment]
@kingdopamine Would you mind creating a new issue for your complaint.  The original problem this issue was created for has been resolved, so to get a fresh pair of eyes on your issue, it is best to create a new issue.   Thank you.

**Comment by djma777** [comment]
LMAO! This is my second round on the lessons and I still got stuck on this one. Been months since my first go, we still haven't fixed this. 💃

**Comment by DanPete** [comment]
Just found the solution from here as well. Had to add 'Home page' to index.pug.

It seems that there still might not be enough direction or the glitch url is cloning an older version of the repo.

**Comment by badrabbitcuntpuncher** [comment]
So I get theses emails in my junk folder all the time, what is
freeCodeCamp? And why is all ur email  conversations go threw my
spam folder?

**Comment by pabloCabrera7** [comment]
The problem is still there, i got stuck quite a long time, hopefully I went to see the forum otherwhise coudnt notice that!
Finally resolve passing the title of Home page...
