### ISSUE TITLE
Incomplete details about how to complete challenge : Create String using Template literal

### ISSUE THREAD

**Issue by mpmaan** [freeCodeCamp/freeCodeCamp#17633]
#### Describe your problem and - if possible - how to reproduce it
It is not mentioned that we should use `map()` function to solve it. The test **Template strings were used** fails if we use a for-loop to solve this challenge. I could pass it by using only `map()` function.

This code works 
```
   const resultDisplayArray = arr.map((item) => `<li class="text-warning">${item}</li>`);
```
This doesn't work
```
    const resultDisplayArray = [];
    for(let i = 0; i < arr.length; i++){
        resultDisplayArray.push(`<li class="text-warning">${arr[i]}</li>`);
    }
```
Most probably the regex test fails because of the `[` and `]` characters while using for-loop.

Also, the `$` characters are not rendered properly in the given example in the guide.
The example should have `${person.name}` and `${person.age}`.

#### Add a Link to the page with the problem
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/es6/create-strings-using-template-literals/

#### Tell us about your browser and operating system

* Browser Name: Google Chrome
* Browser Version: 60+
* Operating System: Ubuntu 18.04

#### If possible, add a screenshot here

![screenshot from 2018-06-19 17-03-28](https://user-images.githubusercontent.com/34267628/41595148-62a3f36a-73e3-11e8-9d5b-e6a31e6b8033.png)

**Comment by Nirajn2311** [comment]
Hmmm, the code appears to be correct in seed, but is not formatted correctly in the webpage.

**Comment by mpmaan** [comment]
@Nirajn2311 Also check this challenge , it has kind of simlar problem.
https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/regular-expressions/use-capture-groups-to-search-and-replace/

**Comment by Nirajn2311** [comment]
I’ll see what I can do about the typos.
For everyone, I would appreciate if you told me all typos anyone finds as I am fixing it at curriculum repo(https://github.com/freeCodeCamp/curriculum/pull/23).

**Comment by mpmaan** [comment]
@Bouncey The issue with `$` sign may have been fixed but what about the `map()` function ?

**Comment by scissorsneedfoodtoo** [comment]
@mpmaan, thank you for pointing out the issue with the formatting caused by MathJax. That was my fault for not checking how it affected all the challenge descriptions outside of the Interview Prep sections.

You're right that there is still an issue with this challenge due to the regex in the test being to specific. You can follow the discussion here: https://github.com/freeCodeCamp/freeCodeCamp/issues/16358

I plan on submitting a fix from one of my comments in that issue.

**Comment by mpmaan** [comment]
@scissorsneedfoodtoo thanks, i am sorry for creating duplicate issue.

**Comment by scissorsneedfoodtoo** [comment]
@mpmaan, no worries! Better a duplicate issue than one going completely unreported. Good looking out!

**Comment by youngtechlove** [comment]
Hi im looking for anyone willing to help me out with some training tips and how i can improve myself at code entry's
