### ISSUE TITLE
Can't access the curriculum page on Firefox

### ISSUE THREAD

**Issue by smartdev007** [freeCodeCamp/freeCodeCamp#18012]
#### Describe your problem

Whenever I try to access the curriculum page on Firefox I get “Corrupted Content Error”. I can access it on chrome but can't access it on Firefox.

#### Tell us about your browser and operating system

* Browser Name: Firefox
* Browser Version: 61.0.2 (64-bit)
* Operating System: Windows 10

#### Screenshot

![screenshot 284](https://user-images.githubusercontent.com/16380239/44098957-23f709d4-9fff-11e8-9861-a4b96b4ffb6e.png)

**Edit:** One thing that I forgot to mention is this only happens when I am logged in. I can access the page if I sign out of my account.

**Edit 2:** Solution and cases to recreate the problem

**Temporary solution** (Credits to @huyenltnguyen )

1. Sign out of the FCC
2. Clear cookies & cache
3. Sign in via https://www.freecodecamp.org/
4. Access the challenges using https://learn.freecodecamp.org/

**Cases to recreate the error** (Credits to @huyenltnguyen )

- If you're on the challenge page and hit refresh
- If you're on the https://learn.freecodecamp.org/ and open a challenge in a new tab (credit to @cj-sv for pointing this out)
- If you click on the 'Go to the coding curriculum' button

**Edit 3:** All the previous cases are working so, **the issue is fixed** now.

**Comment by Nirajn2311** [comment]
Could a post a screenshot of your web console. The web console can be found at `Web Developer` in the menu or by clicking `Ctrl+Shift+K` .

**Comment by Nirajn2311** [comment]
Even after you refresh(keep it open).

**Comment by smartdev007** [comment]
Yup...still nothing.

**Comment by sanchitbansal10** [comment]
Working perfectly on mine...


    Browser Name: Firefox
    Browser Version: 61.0.2 (64-bit)
    Operating System: Ubuntu 18.0.4

**Comment by huyenltnguyen** [comment]
@smartdev007 How about doing a hard reload (Ctrl + F5)?

**Comment by smartdev007** [comment]
@huyenltnguyen Didn't work

**Comment by Nirajn2311** [comment]
What type of connection are you getting? Is it https or http

**Comment by smartdev007** [comment]
It's https

**Comment by cj-sv** [comment]
I'm getting the same error when accessing any lesson from inside the curriculum page. Tested in safe mode as well. 

- Browser Name: Firefox and Firefox Nightly
- Browser Version: 61.0.1 (64-bit), 63.0a1 (64-bit)
- Operating System: Ubuntu 18.04.1

**Comment by huyenltnguyen** [comment]
I was analyzing it and found that I will get the error if:
- I'm on a lesson page and hit refresh
- I visit a lesson page via a link, for example: https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements

I'm on Firefox 61.0.2, running on Windows 10.

@smartdev007 @cj-sv On what page did you get the error? If you go to http://learn.freecodecamp.org/ and navigate to a lesson page, does the error occur?

**Comment by smartdev007** [comment]
@huyenltnguyen I get the error when I click on "Go to the coding curriculum". If I navigate to the curriculum tab on the top right corner, then I am signed out but can successfully access the page. If I try to sign in, then again I am back to where I was.

![screenshot 288](https://user-images.githubusercontent.com/16380239/44197433-300cab80-a15c-11e8-952d-574e9a77d95f.png)

**Comment by cj-sv** [comment]
@huyenltnguyen Yes, the error occurs when navigation to a lesson page.

**Comment by huyenltnguyen** [comment]
@smartdev007 Seems like you're having two issues at once here. One is the sign in issue and the other is the content not loading issue. Stupid question, but how did you know you were signed out? Because there is a 'Sign in' button at the top-right corner? There is a fix for it in the forum from awhile ago, I could do a quick search to get the link, if you need it.

The 'Go to the coding curriculum' directs you to your current challenge, which basically means you're visiting the challenge via a link, which is the second case that I reported above.

The 'Curriculum' button directs you to https://learn.freecodecamp.org/ and you can go to your challenge from there. I don't get the error if I access the curriculum page with this, though.

---
@cj-sv Just to clarify, did you get the error after visiting https://learn.freecodecamp.org/ then click on a challenge? Also, could you check if there is any error in the browser console?

**Comment by smartdev007** [comment]
> how did you know you were signed out? Because there is a 'Sign in' button at the top-right corner?

This and because none of my progress is saved.

> The 'Curriculum' button directs you to https://learn.freecodecamp.org/ and you can go to your challenge from there

Yes, I can access it from there but as I said, site logs me out if I try to access the curriculum page via that link.

**Comment by huyenltnguyen** [comment]
@smartdev007 Here is the solution I mentioned earlier: https://forum.freecodecamp.org/t/i-can-log-into-freecodecamp-org-but-it-logs-me-out-at-learn-freecodecamp-org/194036/47. I know the poster said the issue has been fixed, but what you're experiencing looks the same, so it's worth a try. Hope it works for you.

---
@cj-sv Any error in the browser console? Sometimes addons can cause unexpected behaviors/errors, so maybe you could try disabling them one by one to see if any of them is the cause.

**Comment by cj-sv** [comment]
@huyenltnguyen Woops, forgot to comment on this. Nope, there aren't any outputs in the console. I've been testing on both add-ons enabled and safe mode with all add-ons disabled.

**Comment by huyenltnguyen** [comment]
@cj-sv I'm wondering if clearing cookies works, but you will be signed out and need to re-login, though. I can't think of any way else to fix the issue, so if you still don't get any luck, my last resort would be switching to Chrome :(

**Comment by cj-sv** [comment]
@huyenltnguyen Oh hey, this may be noteworthy. I noticed I've always been accessing each challenge by opening it in a new tab (via middle click and/or right click). Turns out opening a challenge on a new tab causes the error for me.

Everything seems to work when I access a challenge on the same tab (via left click). 

But the "go to coding curriculum" button on the welcome page still gets the error either way.

**Comment by huyenltnguyen** [comment]
@cj-sv Oh great! So glad it (sort of) works out for you eventually 😄 
I think it's a Firefox issue, since Chrome and even Edge have no problem with FCC.

**Comment by smartdev007** [comment]
@huyenltnguyen Thanks for the link, but didn't work for me. And...that corrupted content error is back again :(

**Comment by huyenltnguyen** [comment]
@smartdev007 So @cj-sv confirmed earlier that accessing the curriculum page via the 'Go to the curriculum' button gives us the error. I don't know if you used that button, but if you did, try visiting the curriculum directly using the link https://learn.freecodecamp.org,

If you still get logged out when visiting the curriculum, let's try log out and re-login to https://www.freecodecamp.org, then go to https://learn.freecodecamp.org directly.

It's also worth trying to clear cache and cookies and re-try the logging in steps.

**Comment by smartdev007** [comment]
> If you still get logged out when visiting the curriculum, let's try log out and re-login to https://www.freecodecamp.org, then go to https://learn.freecodecamp.org directly.
It's also worth trying to clear cache and cookies and re-try the logging in steps.

@huyenltnguyen It worked, thanks! :D 

Though 'Go to the curriculum' button is still broken and needs to be fixed.

**Comment by huyenltnguyen** [comment]
@smartdev007 Phew so glad you're in now! Just curious, how did you do it? Just logged out and logged in again or did you have to clear cache and cookies too?

While you're here, could you give some confirmation on these cases when the error occurs:
- If you're on the challenge page and hit refresh
- If you're on the https://learn.freecodecamp.org/ and open a challenge in a new tab (credit to @cj-sv for pointing this out)
- If you click on the 'Go to the coding curriculum' button

If you could reproduce the error with those cases, since you're the OP, hope you don't mind adding these cases to the original post so it's easier for other people to follow.

**Comment by smartdev007** [comment]
@huyenltnguyen I did both the steps. First I logged out of the FCC and then cleared the cache and cookies. Then I went to https://www.freecodecamp.org/ and logged in. After that, I accessed the challenges using this link: https://learn.freecodecamp.org/ and it worked.

I had already tried clearing cookies and cache before creating this issue but didn't follow the steps that you mentioned here. 

And yeah, I get the error with all the three cases that you mentioned.

I have updated the original post. See if the changes are correct and let me know if you want me to make any other changes. (Pretty new to the GitHub so, sorry if I have mentioned any wrong info :P)

**Comment by huyenltnguyen** [comment]
@smartdev007 Thanks a lot for the info on the steps to login and for updating the original post. It looks good to me. I'll try looking into the issue over the weekend, see if I could find the cause.

Anyway, happy coding!

**Comment by huyenltnguyen** [comment]
Okay, I think I know why we got the 'Corrupted Content Error' here. It doesn't matter how we access a challenge page. The thing that matters is the challenge page url.

If you go to https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/say-hello-to-html-elements, you will get the error. But if you add a trailing slash `/` to the url, it works. Chrome and Edge automatically add the trailing slash for us, but Firefox doesn't, thus the error.

**Comment by cj-sv** [comment]
@huyenltnguyen Firefox 61.0.1 and Firefox Nightly 63.0a1 adds the trailing slash for me automatically. Though, all the previous test cases seems to be working now. We'll need @smartdev007 to confirm.

**Comment by huyenltnguyen** [comment]
@smartdev007 @cj-sv It's working for me, too. I guess it's a temporary issue of Firefox then.

Thanks for being through all the hassle with me. Have a nice weekend and happy coding!
