### ISSUE TITLE
Just Wondering

### ISSUE THREAD

**Issue by Deionta1** [FreeCodeCamp/FreeCodeCamp#2352]
Challenge http://www.freecodecamp.com/challenges/waypoint-target-html-elements-with-selectors-using-jquery has an issue. Please describe how to reproduce it, and include links to screenshots if possible. On this challenge I'm trying to figure out if I got the right code or not. I talk to a camper about this challenge and he said there was bugs, but they have been fixed. So I'm just wondering if its me or not. My code is

```js
           <script>
            $(document).ready(function() {
              $("button").addClass("animated bounce");
                  });
               </script>

```

**Comment by benschenker** [comment]
Thanks for posting!

It looks like you got cut off.  Feel free to finish your question and please post a screenshot of the issue.

**Comment by BerkeleyTrue** [comment]
I've edited to display code. Please see https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by benschenker** [comment]
@Deionta1 I don't see an issue with your code.  It looks like it should pass.  Is it working now?

**Comment by Deionta1** [comment]
I thank you for responding, but it is still not working. The challenge keeps telling me to Use JQuery addClass() function to the give the classes animated and bounce to your button elements. I believe that I have done that in the code. Some of my other challenges in Jquery is also doing the same thing as this challenge.

**Comment by benschenker** [comment]
Can you post a screenshot of the issue exactly?

**Comment by MysticRiver** [comment]
I'm having the same issue.
I entered the correct code but it won't recognize it as valid and then take me to the next challenge.
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/2208459/9425605/64b98876-48db-11e5-894a-abc1e14acd01.png)

**Comment by Deionta1** [comment]
Yeah we are having the exact same problem. I have been talking to Ben Schenker, he's apart of freecodecamp and he asked for a screenshot of the problem, so I guess if you send him your screen shot he will let us know how to move forward.

**Comment by Deionta1** [comment]
I appreciate you getting back to me, but the problem has resolved itself and I was wondering if you can help me with something else. On the challenge waypoint: comment your javascript code, when I enter my code and hit the Run code button nothing happens. I've tried to reset it and nothing continues to happen, so I was wondering if I am doing something wrong.

**Comment by BerkeleyTrue** [comment]
@Deionta1 That should be fixed now. Try doing a hard refresh. https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Refresh-Your-Browser-Cache

**Comment by Deionta1** [comment]
I thank you for responding and I was wondering if there is anything else I could do, because I tried your suggestion and still doesn't seem to work.

**Comment by benschenker** [comment]
Have you tried it in incognito mode?

**Comment by Deionta1** [comment]
Yes I have it InPrivate mode and it still does nothing when I click the Run code button.

**Comment by benschenker** [comment]
Do you have a screenshot?

**Comment by Deionta1** [comment]
Sorry for the delay, but this is what it continues to look like even after I have reset it and put it in private mode. No matter what code I put in the editor, or how many times I press the Run Code button nothing happens.

**Comment by BerkeleyTrue** [comment]
@Deionta1 No image is attached. Please use the github website to attach images.

**Comment by Deionta1** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/13397670/9563434/42017d9a-4e51-11e5-8b55-8a83dbf3869e.png)

Sorry this is the screenshot.

**Comment by BerkeleyTrue** [comment]
Due to the browsers limitations, IE/Edge are currently not supported.

**Comment by Deionta1** [comment]
Do you have any suggestions on what I should do next?

**Comment by BerkeleyTrue** [comment]
Does it work for you in Chrome or FF?

**Comment by Deionta1** [comment]
It does work in Chrome, so I just sincerely thank you for that suggestion and all your help over the past week.

**Comment by BerkeleyTrue** [comment]
Awesome. Sorry about the trouble.


Happy Coding!
