### ISSUE TITLE
Invalid solution in a hint

### ISSUE THREAD

**Issue by skhashaev** [freeCodeCamp/freeCodeCamp#34309]
**Describe your problem and how to reproduce it:**
In a hint for conditional operator shown an invalid solution.

**Add a Link to the page with the problem:**
https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 70.0.3538.102 (64-bit)
* Operating System: Windows 10 Home for one language, 64-bit

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/16179239/48364813-69e94180-e6ba-11e8-92f5-1dc13b9377e9.png)
There is an assignment operator instead of the equality operator

**Comment by thecodingaviator** [comment]
This was fixed in PR #34225 it would soon be pushed to master . I'm fixing the formatting of the file.

**Comment by RandellDawson** [comment]
As @thecodingaviator stated above, this has been resolved, but until the changes have been pushed to production, it will still show.  Due to it being fixed, I am closing this issue.

Thank you.

**Comment by RandellDawson** [comment]
**Attention Reviewers:** There are 3 previous PRs  (#22633, #29292, #30038) which make changes to this challenge.

**Comment by LieChou** [comment]
Hi, 

Sorry to get back to you on this topic but it seems that the invalid solution is still showing up : [https://guide.freecodecamp.org/certifications/javascript-algorithms-and-data-structures/basic-javascript/use-the-conditional-ternary-operator/]

I am still having an assignment operator instead of the equality one - which works fine. 

Thank you.

**Comment by thecodingaviator** [comment]
@LieChou the changes have not been pushed to production yet. The changes will appear once the repository is pushed to production

**Comment by LieChou** [comment]
> @LieChou the changes have not been pushed to production yet. The changes will appear once the repository is pushed to production

Ok, thanks.
