### ISSUE TITLE
No typehead on the learn search bar

### ISSUE THREAD

**Issue by coder077** [freeCodeCamp/freeCodeCamp#35432]
**Describe the bug**
There is no typehead on the search bar on the site: learn.freecodecamp.org

**To Reproduce**
1. Go to the main site learn.freecodecamp.org
2. Click on the search bar and type a query 
3. There is no typehead

**Expected behavior**
A typehead is expected.

**Screenshots**
<img width="944" alt="screen shot 2019-02-26 at 7 45 51 pm" src="https://user-images.githubusercontent.com/18624843/53457158-3fb85700-39ff-11e9-9241-8e98a0376bd7.png">

**Comment by RandellDawson** [comment]
@coder077 There have been many changes to the `master` branch which have not yet made it to production.  You can see these changes at https://freecodecamp.rocks.  If you still see these problems on the beta site, then please let us know.  If not, can you please close this issue?

Thank you.

**Comment by RandellDawson** [comment]
I think you might mean `type-ahead` instead of `typehead`.  Another word for this `autocomplete`.

**Comment by RandellDawson** [comment]
@coder077 The search bar does have this feature in a way.  As you type, a dropdown appears below with relevant keywords.  This can be seen on the beta site (freecodecamp.rocks) as the current production site has a bug causing these results to be hidden.  This has been fixed and will eventually be rolled out to the production site.

**Comment by coder077** [comment]
@RandellDawson  Yeah sorry, typeahead was what I meant and thank you for the clarification. Ok, I was unsure if it was an issue because, on the search site, the autocomplete was more "better". But otherwise, this could be closed.

**Comment by joshiad** [comment]
@RandellDawson @coder077 We still have this issue in Safari. 
<img width="1060" alt="screen shot 2019-03-01 at 3 49 40 pm" src="https://user-images.githubusercontent.com/25302817/53665549-bc367a00-3c39-11e9-9ff7-4cd0a08d41e8.png">
