### ISSUE TITLE
Project display on .dev

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#38984]
**Looking forward for reporting a security issue:**
Please report security issues by sending an email to `security@freecodecamp.org` instead of raising a GitHub issue.

**Describe the bug**
QA projects do not seem to be being synced correctly. If I look at my profile immediately after completion, they say 'Show Code' rather than 'ShowSolutions'.  Presumably the problem exists for other certificates, but I have not confirmed.

**To Reproduce**
1. Complete QA certificate
2. click on /learn (top right)
3. click on Update my account settings
4. scroll down to Quality Assurance
5. see at least one 'Show Code' button

**Expected behavior**
Both the project and the repository should be visible on my settings page.

**Screenshots**
I completed the first three challenges earlier (December 2019)
![image](https://user-images.githubusercontent.com/15801806/83414076-2af61a80-a41d-11ea-8bef-ac33a497f17b.png)

after reloading the page they were all correct.

**Additional context**
Related: https://github.com/freeCodeCamp/freeCodeCamp/issues/38918

**Comment by raisedadead** [comment]
I think this is related to a bug we recently fixed. I deployed a new version right about the time this issue was opened. 

Do you want to give it another go? Let me know if you need a reset on the user object that you have been using.

**Comment by ojeytonwilliams** [comment]
I just tried submitting the Port Scanner project and got this:

![image](https://user-images.githubusercontent.com/15801806/83490181-dea7ea80-a4af-11ea-9e57-cb103ccc3413.png)

then I reloaded and got:

![image](https://user-images.githubusercontent.com/15801806/83490366-321a3880-a4b0-11ea-8f91-317e2602d411.png)

so it's not fixed on .dev.

No need to reset the dev account just yet.  I'll let you know when I run out of projects to test.

**Comment by moT01** [comment]
I haven't looked to confirm, but I believe those projects use one of the other views. The stock price checker, for example, must use the backend project template because it has the two urls - which is why it says 'show solutions' (live demo url + github code url). The port scanner must be using the front end project view or something, which only requires one url.

**Comment by ojeytonwilliams** [comment]
Yep, this what I have currently

![image](https://user-images.githubusercontent.com/15801806/84032202-41f5b900-a997-11ea-8e23-d516a1a0c20d.png)

Before I refreshed the page, it was displaying `Show Code` and now it's `Show Solution`.  In other words, yes, it should show a different button, but not this particular one.

I've not looked into this yet, but my guess is that the redux store is not getting updated until page reload and the button defaults to `Show Code`.

**Comment by moT01** [comment]
> my guess is that the redux store is not getting updated until page reload

That sounds right.

I believe there is some other similar problems. I think, for example, that when you claim a cert - then go to your portfolio, it won't be there until you refresh. And possibly something similar when you submit and/or claim legacy projects/certs.

**Comment by ojeytonwilliams** [comment]
Thanks for the heads up and, yep, they're probably all symptoms of the same thing.
