### ISSUE TITLE
ISSUE IN CATS AND DOGS PROJECT

### ISSUE THREAD

**Issue by umair-nasir14** [freeCodeCamp/freeCodeCamp#39313]
**Describe your problem and how to reproduce it:**
The test data is not being found by flow_from_directory() even though if I run !ls  /root/.keras/datasets/cats_and_dogs/test it shows the 50 images. 
It is reading training and validation data but not the test.
![1](https://user-images.githubusercontent.com/68095790/88379437-62010080-cdbc-11ea-87ef-0c6e4268aa5b.png)
![2](https://user-images.githubusercontent.com/68095790/88379442-63322d80-cdbc-11ea-9254-b858563d54d8.png)

**Add a Link to the page with the problem:**
https://colab.research.google.com/drive/1JExptqHMk2x3jqsa_e7tdvGW04V48e-t?usp=sharing

**Tell us about your browser and operating system:**
* Browser Name: Google Chrome
* Browser Version: 84.0.4147.89 
* Operating System: Windows 10 

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**

**Comment by umair-nasir14** [comment]
As far as I have been told, flow_from_directory() expect expects a directory with a subdirectory. Maybe you need to add a directory with in test folder which stores images

**Comment by shraddhavp** [comment]
is the issue open yet?I would like to take up the issue

**Comment by umair-nasir14** [comment]
Yes this issue is absolutely open!

**Comment by umair-nasir14** [comment]
And you're welcome to take up this issue!

**Comment by shraddhavp** [comment]
ok thanks @umair-nasir14  can you tell where I can find the file I am not able to find it

**Comment by umair-nasir14** [comment]
Here's the link:

https://colab.research.google.com/drive/1JExptqHMk2x3jqsa_e7tdvGW04V48e-t?usp=sharing

**Comment by rustyyyyy** [comment]
i have fixed issues you are having here is screenshot of code
![Screenshot (41)](https://user-images.githubusercontent.com/42319153/98759035-47e53f80-23f8-11eb-85ed-c8c9b7e73d8c.png)

**Comment by rustyyyyy** [comment]
https://colab.research.google.com/drive/1JExptqHMk2x3jqsa_e7tdvGW04V48e-t?usp=sharing

**Comment by rustyyyyy** [comment]
link of code fixes 

https://colab.research.google.com/drive/1Ifu_qLobX6ohutmac-M3GIdgB8eBPTqh?usp=sharing

**Comment by raisedadead** [comment]
Sorry for the delay in getting back. We seemed to have missed taking a look at this.

I took a quick cursory look and could not determine if this is an actual bug or something to do with the the shared notebooks in this thread.

Could you confirm the issue still persists on the challenge: https://www.freecodecamp.org/learn/machine-learning-with-python/machine-learning-with-python-projects/cat-and-dog-image-classifier and the official boilerplate linked in the challenge?

If yes, please create a fresh issue thread with the details. 

However, if you are/were looking for support on the challenge, we recommend asking for the same on the forum.

Thanks & happy coding.
