### ISSUE TITLE
RDB Beta - Redirect to landing page after CodeAlly login

### ISSUE THREAD

**Issue by slittleton** [freeCodeCamp/freeCodeCamp#45553]
Attempting to login using Github with "powered by CodeAlly" and choosing a course redirects to landing page causing endless loop.

Expected behavior:
After doing the login process one time it should allow user to access curriculum instead of redirecting to landing page.

Actual Behavior:
Endless loop of logging in and choosing a course to login and choose a course to login and choose a course.

Steps:
1) go to freecodecamp landing page (https://www.freecodecamp.org/)
2) click "Get Started"
3) Choose tutorial Type (ex: Relational Databases)  
4) Select Course (https://www.freecodecamp.org/learn/relational-database/learn-bash-by-building-a-boilerplate/build-a-boilerplate)
5) Click on "Click Here to Start Course"
6) Redirected to login using "CodeAlly"
7) Login using Github account with CodeAlly
8) Redirected to freecodecamp landing page

URL:
https://www.freecodecamp.org/

Browser:
Brave

OS:
Ubuntu 20.04

NOTE: Seems to work fine on Chrome with Windows 11, but not on Brave with Ubuntu

**Comment by gikf** [comment]
Brave seems to be by default blocking third-party cookies from CodeAlly, hence the authorization loop. Once those cookies are allowed tutorial loads fine. This probably doesn't qualify as a bug.

**Comment by AdamZaczek** [comment]
Hello, CodeAlly founder here. I took a look into this.
It's about first-party cookies - local storage.
When CodeAlly is embedded, Brave thinks it's some sort of ad.

Brave blocks CodeAlly from working inside Freecodecamp.
To overcome this, CodeAlly's essential cookies have to be enabled.

Note: Enabling cookies manually is not needed when CodeAlly is used without embedding. I didn't check the source code of Brave but it appears the mechanism works like this:
embedded app === probably an ad

This is a sane approach to blocking most annoying ads but unfortunately, adds a little bit of overhead when running tutorials.
Thanks for reporting @slittleton.

**Comment by AdamZaczek** [comment]
Hello, CodeAlly founder here. I took a look into this.
It's about CodeAlly's first-party cookies - local storage.
When CodeAlly is embedded, Brave thinks it's some sort of ad.

To overcome this, CodeAlly's essential cookies have to be enabled.

Note: Enabling cookies manually is not needed when CodeAlly is used without embedding. I didn't check the source code of Brave but it appears the mechanism works like this:
embedded app === probably an ad

This is a sane approach to blocking most annoying ads but unfortunately, adds a little bit of overhead when running tutorials.
Thanks for reporting @slittleton

**Comment by nhcarrigan** [comment]
Unfortunately this seems like an issue specific to Brave, and not something we can realistically fix.

@moT01 Should we add a note to the forum post for this?

**Comment by raisedadead** [comment]
This is actually a third-party cookie issue. 

We need to be able to detect & display a user a message that they need to enable third-party cookies for CodeAlly.

I propose we continue with the technical details in the linked thread on the CodeAlly-CodeRoad-freeCodeCamp meta repo instead.

**Comment by Sboonny** [comment]
I am wondering if this should be closed with Tom PR?

**Comment by AdamZaczek** [comment]
It looks like it should @Sboonny . Thanks everyone for the help with this issue.

**Comment by jez120** [comment]
Redirection back to origin site endless loop in Chrome, what should I do ? I am doing freecodecamp Learn Relational Databases by Building a Mario Database?

**Comment by AdamZaczek** [comment]
Could you post a video @jez120 so I can try to reproduce it?

**Comment by AdamZaczek** [comment]
Thank you, for reporting @jez120 . I've fixed one issue that you might have experienced. Let me know if it was the one since I don't have many. details

**Comment by jez120** [comment]
Hi Adam thanks for your prompt response. Yes I am able to log on to Building a Mario Database. I like your Boilerplate course and also Mario Datase so far. Thanks and regards.

**Comment by AdamZaczek** [comment]
Awesome, I'm glad to hear that. Have fun coding @jez120!

**Comment by taylorafox1** [comment]
I'm having the same issue on Chrome trying to access the bash programs course and SQL part 1 course. I have cookies enabled but still getting stuck when it tries to redirect after logging in to codeally with my github signin.

**Comment by santiagotorregallego** [comment]
Hello everyone, hello AdamZaczek, I try and try to load the page where the RunCodeAlly button appears, but it doesn't. I have read the forum, I also allowed cookies in Chrome but nothing that allows me.
Yesterday it allowed me and in fact I made my first bash tutorial.

Greetings.

**Comment by AdamZaczek** [comment]
We had a now-fixed error that was probably causing this. Please let me know if it works for you now @santiagotorregallego

**Comment by santiagotorregallego** [comment]
Hello @AdamZaczek , since this morning it works very well for me, I thank you for your attention and for all this wonderful contribution that you have given to humanity

**Comment by mdezetter** [comment]
I've been having this same issue on Firefox for a while now. Any ideas on how to fix it?

**Comment by moT01** [comment]
Make sure you have third-party cookies enabled @mdezetter - and check your security settings for something that might be blocking them. I have been using firefox without issue for quite some time.

You can also check [this post](https://forum.freecodecamp.org/t/running-the-relational-database-curriculum-in-your-browser/500231) for a bunch of instructions and troubleshooting tips. Let us know if you are still stuck.

You could try chrome, as well - but you will likely run into the same issues if those cookies are blocked.

**Comment by mdezetter** [comment]
> 

Thank you, yeah I've gone through the post several times and nothing helped. I've made sure I have firefox set to allow all cookies from freecodecame, codeally, and github. I also disabled all my privacy related extensions. Then when all else failed. I tried in incognito and it still gets me stuck in this infinite loop.

**Comment by moT01** [comment]
Here's my firefox security settings:
![Screen Shot 2022-08-19 at 12 23 20 PM](https://user-images.githubusercontent.com/20648924/185674059-21be56a1-4b31-4c6a-8492-026b7da6cbe6.png)

Chrome didn't work either for you? Do you see anything in the dev tools that may be helpful - the console or network tab? Maybe clear any cookies and local storage related to the CodeAlly domain and try again?

**Comment by mdezetter** [comment]
Aha okay so for anyone else that hits this issue in Firefox. It's content blocking, not cookies. So even though I had third party cookies set to always allow. It was still content blocking. I turned this off by going to the freecodecamp course page, clicking the shield next to the URL and turning off the toggle for content blocking.

**Comment by douglasboardman** [comment]
Thank you @mdezetter, your solution really helped me. I was facing the same issue in Firefox.
Now my browser is 'Firefixed' ;)

All the best
