### ISSUE TITLE
Waypoint: Uncomment HTML - 4th test fails, is malformed?

### ISSUE THREAD

**Issue by Markarvis** [FreeCodeCamp/FreeCodeCamp#4961]
Challenge [Waypoint: Uncomment HTML](http://www.freecodecamp.com/challenges/waypoint-uncomment-html#?solution=%3Ch1%3EHello%20World%3C%2Fh1%3E%0A%3Ch2%3ECatPhotoApp%3C%2Fh2%3E%0A%3Cp%3EHello%20Paragraph%3C%2Fp%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html
<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>

```

**Comment by AndreeVela** [comment]
I confirm the issue. The same thing is happening to me.

**Comment by SaintPeter** [comment]
Here is the 4th test:
![image](https://cloud.githubusercontent.com/assets/553494/11550722/3e2e6018-9927-11e5-8e7d-6095d1fd47cc.png)

Here is the relevant code:
`"assert(!new RegExp(\"-->\", \"gi\").test(code), 'message: Be sure to delete all trailing comment tags&#44; i.e. <code>--&#62;</code>.');"`

Looks like the split regex is splitting on the first comma.

**Comment by BerkeleyTrue** [comment]
This was actually do to an earlier version that was fixed with https://github.com/FreeCodeCamp/FreeCodeCamp/pull/4957/files. This should be fixed now in production.

![waypoint__uncomment_html___free_code_camp](https://cloud.githubusercontent.com/assets/6775919/11550894/14ca4b9a-9929-11e5-80ac-89249e5bc4b1.png)

**Comment by BerkeleyTrue** [comment]
This is fixed now

Happy Coding!

**Comment by hautemum36** [comment]
Hello,

I am having an issue with in commenting trailing comments, I am unable to move past  this challenge although my code is correct.

**Comment by ltegman** [comment]
@hautemum36 Please copy and paste your code for the challenge that is not passing.

**Comment by esmith98** [comment]
I am having issue with the comment trailing as well!

<h1>Hello World</h1>

<h2>CatPhotoApp</h2>

<p>Hello Paragraph</p>

**Comment by Jillianleeadamson** [comment]
As I'm having this problem 10 months later, I don't think it's fixed...

This is my code:

<h1>Hello World</h1>
<h2>CatPhotoApp</h2>
<p>Hello Paragraph</p>

Am I doing something wrong?

**Comment by texas2010** [comment]
@Jillianleeadamson, 
Please use the [Help chat room](https://gitter.im/FreeCodeCamp/Help) for getting challenge related help.
Sorry, This issue place for not ask help.  Better way, ask help at chat room or forum.
Happy Coding.
