### ISSUE TITLE
Learn Fetch and Promises by building an FCC authors page unit test issue

### ISSUE THREAD

**Issue by mESmaC** [freeCodeCamp/freeCodeCamp#55322]
### Describe the Issue

step 18, step 19
While doing template literals on the authorContainer.

you need to refresh the page in order to check the code successfully.

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

Steps to reproduce:

1: answer the question.
2: try to submit.
3: The unit test will tell you need to create the element even though it already exists.
4: refresh the page with CTRL+R
5: press submit immediately and it will accept the solution and pass the unit test.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-fetch-and-promises-by-building-an-fcc-authors-page/step-18

### Your code

```
// The issue code was specifically the P tag and the A tag 
const displayAuthors = (authors) => {
  authors.forEach(({ author, image, url, bio }, index) => {
    authorContainer.innerHTML += `
    <div id="${index}" class="user-card">
      <h2 class="author-name">${author}</h2>
      <img class="user-img" src="${image}" alt="${author} avatar" />
      <p class="bio">${bio}</p>
      <a class="author-link" href="${url}" target="_blank">${author}'s author page</a>
    </div>
  `;
  });
};
```

### Expected behavior

I expected to answer correctly and be able to submit, but i needed to refresh the page before it accepted the answer.

### System

- Device: Mac Mini Mid 2011 5,2
- OS: Lubuntu 24.04 LTS
- Browser: Chrome
- Version: Version 126.0.6478.114 (Official Build) (64-bit)

### Additional context

When trying to reproduce by going to the affected steps, the issues appears to occur only some of the time.

**Comment by salaahl** [comment]
The problem seems to be browser related. I managed to reproduce the bug with Microsoft Edge (125.0.2535.67) and Google Chrome (125.0.6422.142) but not under Firefox (version 91.11.0)

**Comment by salaahl** [comment]
It didn't change anything. While doing my research regarding the error code for example, I realized that two tests returned the same text, in particular one containing a regex. This one for the first (step 27) :

You should create a `p` element.

```js
assert.exists(document.querySelector('p'));
```

And this one for the second (step 18) :

You should create a `p` element.

```js
assert.match(code, /<p\s*/)
```

Could this be related?

**Comment by lasjorg** [comment]
The tests in step 27 can not affect steps 18/19.

I would assume that the `p` test in step 27 is just to make sure the camper does not alter the existing code when adding the ternary.

> It didn't change anything.

Are you sure you disabled the cache?

I wasn't able to reproduce it with the cache disabled, but then I often wasn't able to reproduce it anyway.

Like I said, it is pretty random. I'm fairly sure something is throwing an error that is never recovered from, so it ends up in a state that can only be fixed by a refresh.

**Comment by salaahl** [comment]
I even changed computers several times. I cloned the project locally with the idea of ​​making certain modifications but I can no longer trigger the error. Even online it's actually quite random...

**Comment by lasjorg** [comment]
Having seen this myself and seeing it reported on the forum at least a few times, I think it is safe to say this is confirmed.

Unfortunately, I have no way of reproducing it consistently and no real answer to the cause. My best guess remains, it is somehow related to the fetch. The fetch is triggered on every code change, so maybe a temporary syntax error (when writing the code, before it is completed) combined with the fetch. I just don't know.

**Comment by naomi-lgbt** [comment]
Just to clarify, are we able to confirm that triggering a preview refresh (by editing the code, adding a console log anywhere is a good way to do this) does NOT resolve the state issue?

**Comment by lasjorg** [comment]
I don't think (remember) that triggering an update by editing the code did anything. I think you have to refresh the page, and/or copy the code, reset and paste it back in (to avoid triggering the bug again by manually writing the code).

Trigger the bug is pretty random, so it isn't that easy to test it.

**Comment by mcehme** [comment]
Steps I've used to replicate:
Browser: Chrome Incognito
OS: Windows 11
Note: replication only possible on fcc server. Not possible using gitpod.io.

1. Open new incognito window
2. Navigate to step 18 or 19
3. Run the test once before writing any code causing it to fail
4. Copy and paste the step's solution into the editable region. You **must** copy and paste.
5. Run the test again, it should fail. **Do not** run with the dev console open. It will pass if the dev console is open.

I've done some poking, and I see the tests are implemented by adding a script tag to the bottom of the html body (after the script tag for the user script). However, I don't see any mechanism to guarantee the user script finishes executing before the tests start. In synchronous programming, placing the test script after the user generated script guarantees the behavior we want. However since we are using promises, we cannot rely on this assumption.

Unfortunately, I cannot replicate the bug on my gitpod.io dev server. However, the frame-runner script is loaded remotely, and we would expect it to load significantly slower on gitpod.io compared to the fcc prod server. This makes testing a solution difficult.

**Proposed Solution:**
We simply add a busy wait loop to give the user script time to complete. We need only delay on the first test, and I believe 100ms should more than suffice.

**Comment by mcehme** [comment]
Found the below snippet in step 17, I will make a PR copying the code over to steps 18, 19, and 26. (I was able to verify the same issue in 26).
```
const retryingTest = (test, message, tries = 20) => {
  if (tries < 1) return Promise.reject(message);
  if (test()) return Promise.resolve();

  return new Promise((resolve, reject) => {
    setTimeout(() => {
      retryingTest(test, message, tries - 1)
        .then(resolve)
        .catch(reject);
    }, 100);
  });
};
() => retryingTest(() => document.querySelector('img'), "'img' element not found");
```

**Comment by moT01** [comment]
I could not reproduce it with these:
-Firefox 128.0 (authed and private)
-Chrome 126.0.6478.183 (authed and incognito)
-Safari 17.4.1 (authed | non-authed)

I was finally able to reproduce it with these:
-Safari 17.4.1 (private)
-Opera 109.0.5097.80 (non-authed | private)

So to reproduce, I followed @mESmaC's instructions - go to step 18, running the tests before changing any code (sometimes this didn't seem required), copying the seed of 19 to step 18 and run the tests again.

Like mentioned, it happens on steps 18, 19, and 26. I could not reproduce it on several other steps I tried.

Do you know what might be causing this @mESmaC - I want to say it has to do with the fetch, but that's on every step in the project. Why would it only happen on certain steps? If we are waiting for the user script to finish, why is it only on certain steps. I'm not putting it together.

I think the proposed solution might work in this instance, but I'm wondering if there's any other solutions we can use here - like a more global solution. It would be nice to pinpoint the issue.

**Comment by mcehme** [comment]
All the steps except the following use regex on the code text in their tests: 12, 13, 17, 18, 19, and 26. 12 and 13 are directly testing the displayAuthors function and don't rely on fetch executing. In other words, 17, 18, 19, and 26 are the only tests that actually look at the results of the fetch.

**Comment by moT01** [comment]
Okay, thanks for clarifying. I would fine with your solution for now if it works 👍
