### ISSUE TITLE
Doesn't accept single quotes

### ISSUE THREAD

**Issue by RFenolio** [FreeCodeCamp/FreeCodeCamp#5666]
When you solve this problem using single quotes, it doesn't recognize the += operator, so the test doesn't pass. It's not obvious that you need to use double quotes, nor should it be necessary.

Challenge [Waypoint: Concatenating Strings with the Plus Equals Operator](http://www.freecodecamp.com/challenges/waypoint-concatenating-strings-with-the-plus-equals-operator#?solution=%2F%2F%20Example%0Avar%20ourStr%20%3D%20%22I%20come%20first.%20%22%3B%0AourStr%20%2B%3D%20%22I%20come%20second.%22%3B%0A%0A%2F%2F%20Only%20change%20code%20below%20this%20line%0A%0Avar%20myStr%20%3D%20%22This%20is%20the%20first%20sentence.%20%22%20%3B%0AmyStr%20%2B%3D%20%22This%20is%20the%20second%20sentence.%22%3B%0A%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```javascript
// Example
var ourStr = "I come first. ";
ourStr += "I come second.";

// Only change code below this line

var myStr = 'This is the first sentence. ' ;
myStr += 'This is the second sentence.';


```

**Comment by ltegman** [comment]
Hmm, looks like we had a PR to fix this on the challenge using the `+` operator, but not the one using the `+=` operator. Good catch!

**Comment by pmbenjamin** [comment]
Looking into this now.

**Comment by pmbenjamin** [comment]
@ltegman I don't see that the challenge using `+` was fixed to include single quotes as a valid solution. I was looking for it to see how that one was resolved just for consistency's sake.

**Comment by pmbenjamin** [comment]
@ltegman never mind, I just found it. I'm sorry, didn't look in the right place.

**Comment by RFenolio** [comment]
it should be the [\"'] in the regex that gives both options

**Comment by pmbenjamin** [comment]
:+1: 
yup, found it. Wasn't looking in the right place, but ultimately found it. Testing it now on my local copy before submitting PR request.

**Comment by ar94952** [comment]
As far as I know, my answer should correct.  
Code:
var ourStr = "This is the first sentence. ";
ourStr += "This is the second sentence.";

Still having issues.

**Comment by hrsa2017** [comment]
var ourstr = 'This is the first sentence. ' ;
ourstr += 'This is the second sentence.';

**Comment by musasesay** [comment]
var myStr = 'This is the first sentence. ' ;
myStr += 'This is the second sentence.';
