### ISSUE TITLE
Curriculum Helper .functionRegex doesn't (seem to) support `const foo = function (bar) {}`

### ISSUE THREAD

**Issue by l3onhard** [freeCodeCamp/freeCodeCamp#64067]
### Describe the Issue

While developing the `workshop-word-counter` (https://github.com/freeCodeCamp/freeCodeCamp/pull/64012) I wrote a test to ensure learners created a function with a specific parameter using the Curriculum Helper `.functionRegex`. I borrowed this approach from step 6 of the `workshop-calculator`. However, during manual testing I discovered the test fails incorrectly when learners create a function like `const foo = function (bar) {}`. The test passes with `function foo (bar) {}` and `const foo = (bar) => {}`. This suggests `.functionRegex` doesn’t support `const foo = function (bar) {}`.

Here is the test from [workshop-calculator/step-6](https://github.com/freeCodeCamp/freeCodeCamp/blob/aa3656b74b9e8231fef83dd6da4f37c1c233199a/curriculum/challenges/english/blocks/workshop-calculator/66cc0f1ae40802781b2ea972.md?plain=1#L33C1-L38C4):

````md
Your `calculateSum` function should take two parameters, `num1` and `num2`.

```js
const regex = __helpers.functionRegex('calculateSum', ['num1', 'num2']);
assert.match(__helpers.removeJSComments(code), regex);
``` 
````

### Affected Page

https://www.freecodecamp.org/learn/javascript-v9/workshop-calculator/step-6

### Your code

```js
const calculateSum = function (num1, num2) {}
```

### Expected behavior

This solution should pass the test.

### Screenshots

<img width="1461" height="802" alt="Image" src="https://github.com/user-attachments/assets/09579cf6-fafe-4749-89d8-c6689b56721a" />

### System

- Device: Laptop
- OS: macOS 26.1
- Browser: Firefox
- Version: 145.0b9 (aarch64)

**Comment by majestic-owl448** [comment]
> This suggests `.functionRegex` doesn’t support `const foo = function (bar) => {}`.

that is not a syntax that is allowed in JavaScript, but
 - named `function` keyword function passes
 - arrow function passes
 - anonymous `function` keyword function is not passing

is this something we want to allow? an anonymous function is not really a named function, but arrow functions are also anonymous and we allow those

this is `.functionRegex`:

https://github.com/freeCodeCamp/curriculum-helpers/blob/5571feccdf1c68bec82a685c3c83d70b60f8961c/packages/helpers/lib/index.ts#L241-L268

**Comment by l3onhard** [comment]
My apologies, I meant to write `const foo = function (bar) {}` following the pattern in the screenshot. I’ll edit the issue to fix this.

**Comment by l3onhard** [comment]
I expected the anonymous function (declared with the `function` keyword `const foo = function (bar) {}`) to pass, because learners are introduced to this kind of function declaration in the preceding lesson `what-is-the-purpose-of-functions-and-how-do-they-work`:

<blockquote>
So far, we've been working with named functions, but you can also create what's called an anonymous function. An anonymous function is a function without a name that can be assigned to a variable like this:

<pre>
const sum = function (num1, num2) {
  return num1 + num2;
};

console.log(sum(3, 4)); // 7
</pre>
</blockquote>

You can find the whole lesson here: https://www.freecodecamp.org/learn/javascript-v9/lecture-working-with-functions/what-is-the-purpose-of-functions-and-how-do-they-work

**Comment by majestic-owl448** [comment]
as it say, that one is without a name, in this step you are asked to create a function that has a specific name

it is also possible to argue that assigning the function to a variable is also giving it a name tho

**Comment by l3onhard** [comment]
Yes, the instructions ask for the function to be named. However, while `const calculateSum = function (num1, num2) {}` and `const foo = (bar) => {}` create anonymous functions, they still pass the first test:

````md
You should declare a function called `calculateSum`.

```js
assert.isFunction(calculateSum);
```
````

This raises the question of whether we should make the first test more strict. However, why would we restrict learners to a single type function declaration?

**Comment by majestic-owl448** [comment]
then let's update the helper

**Comment by nafiudanlawal** [comment]
Hello @majestic-owl448 and @l3onhard. I have created a pull request in the curriculum-helper repo to address this issue. It adds checks for declaration of function expressions.

Here is the merge request https://github.com/freeCodeCamp/curriculum-helpers/pull/549

**Comment by nafiudanlawal** [comment]
The fix has been merged in the curriculum-helpers repo. I think we can close this issue now. @majestic-owl448 

https://github.com/freeCodeCamp/curriculum-helpers/pull/549

**Comment by majestic-owl448** [comment]
@nafiudanlawal if you had linked to this issue it would have closed automatically

**Comment by l3onhard** [comment]
When will the PR by @nafiudanlawal (freeCodeCamp/curriculum-helpers#549) go into production? 

When I tested [step 6 of workshop-calculator](https://www.freecodecamp.org/learn/javascript-v9/workshop-calculator/step-6) today, the test still failed with `const calculateSum = function (num1, num2) {}`: 

![image](https://github.com/user-attachments/assets/7515116f-3009-4c88-a653-d13eb4dedf2f)

**Comment by majestic-owl448** [comment]
first curriculum helpers need to be released, which requires a PR similar to https://github.com/freeCodeCamp/curriculum-helpers/pull/519 and a release on the npm registry (https://www.npmjs.com/package/@freecodecamp/curriculum-helpers)
 
then the dependency needs to be updated in this repo, a PR similar to https://github.com/freeCodeCamp/freeCodeCamp/pull/62954

this is the thanksgiving weekend, it will happen eventually, but not immediately

after that, a deployment of the freeCodeCamp site is needed
