### ISSUE TITLE
Example project is broken

### ISSUE THREAD

**Issue by mmatthews1981** [FreeCodeCamp/FreeCodeCamp#8021]
Challenge [Show Relationships with a Force Directed Graph](https://www.freecodecamp.com/challenges/show-relationships-with-a-force-directed-graph) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

The example project http://codepen.io/FreeCodeCamp/pen/KVNNXY isn't rendering.

**Comment by erictleung** [comment]
@mmatthews1981 I think one reason it doesn't render is because Free Code Camp doesn't use the News section on the site anymore, since it moved news and discussion over to Reddit. @FreeCodeCamp/issue-moderators correct me if I'm wrong on this.

**Comment by sludge256** [comment]
@erictleung The link still works if it's updated to `https`.

Closing as https://github.com/FreeCodeCamp/FreeCodeCamp/issues/7700 addresses this.

**Comment by keccakec** [comment]
I would just like to add that I just opened it with https and it is still blank. I tried in Chrome, Firefox, and Firefox mobile and on all of them it is just a brown page with a blank container that has a box shadow.

**Comment by erictleung** [comment]
@raisedadead if you have access to the FCC account on CodePen, the variable `URL_News` in the JavaScript code needs an `https`:

```js
var URL_News = 'https://www.freecodemp.com/news/hot';
```

Ah looks like we missed [the description](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7884/commits/086c6149b1b36fb39164d33ceb73305ec84936f5#diff-2d1132e2e945b55d59a8b78041af730cR133) in your last PR too.

**Comment by arsho** [comment]
I am also unable to view anything on the codepen URL no matter I am using HTTPS or HTTP. 
![error](https://cloud.githubusercontent.com/assets/5465070/14516530/bc9d4164-0225-11e6-907c-963f41906151.png)

**Comment by erictleung** [comment]
@arsho if you just briefly take a look at [the code](http://codepen.io/FreeCodeCamp/pen/KVNNXY), look at the JavaScript (JS) section and add an `s` to the link in the `URL_News` variable and you should then be able to see things move.

**Comment by hallaathrad** [comment]
Who's got access to the account? we need that in order to update the var like @erictleung's said

**Comment by raisedadead** [comment]
@hallaathrad I have got access. I'll take care of this asap.

**Comment by sludge256** [comment]
@erictleung Sorry, I should have been more specific about which link I was talking about.

I thought this part of #7700 addressed it:
![datavis](https://cloud.githubusercontent.com/assets/10524623/14516705/9de6204e-01ba-11e6-8d86-fb26390ea535.PNG)

**Comment by raisedadead** [comment]
@mmatthews1981 @erictleung @hallaathrad @sludge256 I just updated it. Please refresh

**Comment by raisedadead** [comment]
And we have yet to find a data set for this challenge hence that is not addressed in the PR.

**Comment by raisedadead** [comment]
@sludge256 @erictleung Please close after confirmation. Thanks.

**Comment by erictleung** [comment]
@raisedadead CodePen looks good! This issue should stay open. The [text for the link](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/7884/commits/086c6149b1b36fb39164d33ceb73305ec84936f5#diff-2d1132e2e945b55d59a8b78041af730cR133) for the Camper News Hot Stories API needs to be changed to `https`.

**Comment by erictleung** [comment]
Closing as the example project is no longer broken. Happy coding, y'all!

**Comment by arsho** [comment]
I see the url has been updated but I am still getting the following error message in the console. 

![newserror](https://cloud.githubusercontent.com/assets/5465070/14517097/759576be-022b-11e6-9b24-9c78f1aafcc6.png)

**Comment by raisedadead** [comment]
@arsho have you checked the codepen with `https` as in :

https://codepen.io/FreeCodeCamp/pen/KVNNXY

**Comment by arsho** [comment]
@raisedadead , I tried the codepen with `https` but still no luck. I also cleared my browser cached files. I am using Chrome Version 49.0.2623.75 (64-bit) on Ubuntu 15.04 machine. Here is the screenshot:
![camperchrome](https://cloud.githubusercontent.com/assets/5465070/14548058/504131f0-02d5-11e6-8934-6bda03fa2558.png)

**Comment by dwd2010** [comment]
no what?  that issue is fixed. @raisedadead. I checked on that pen. it is fine now

**Comment by raisedadead** [comment]
@dwd2010 Its broken for me. It was working earlier.

@ahstro This is weird behaviour. strange.

**Comment by dwd2010** [comment]
@raisedadead, odd. I just did checked that pen few mins ago. it is fine to me.

**Comment by raisedadead** [comment]
Confirmed.

User agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by arsho** [comment]
@raisedadead , 
While accessing the url [https://www.freecodecamp.com/news/hot](https://www.freecodecamp.com/news/hot) directly from browser, I get the following confirmation page.
![newshoterror](https://cloud.githubusercontent.com/assets/5465070/14551905/c0a03ad4-02fa-11e6-9d9a-b9fe4df1a1ac.png)

Is it causing problem in Codepen Javascript code too?

**Comment by BerkeleyTrue** [comment]
@ahstro That is unrelated. You are using an ISP or VPN that CloudFlare (our DNS provider) has marked suspicious do to prior malicious activity.

**Comment by raisedadead** [comment]
Yup @arsho Unfortunately, I am also behind a shady ISP. This works perfectly when I switch to a different network.

Sorry about the inconvenience and I share the frustration, but closing this as nothing can be done on FCC side.

**Comment by arsho** [comment]
@raisedadead , Ya, I am using shared broadband internet connection that may or may not be used for suspicious activity, I have no idea. I also cannot switch to any different network at this moment. 

@BerkeleyTrue,
I am confident that other campers from Bangladesh will also face the same problem. Currently I am working the challenge by downloading the json object from the browser locally. 

I have a suggestion that the API can be referred to a link in github as the other D3 challenges as it is nothing but to learn D3. It does not need actual real time value. If the link collects data from Github, everyone can use it without facing any problem.
