### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by FSou1** [FreeCodeCamp/freecodecamp#988]
Challenge http://www.freecodecamp.com/challenges/waypoint-add-placeholder-text-to-a-text-field has an issue. Please describe how to reproduce it, and include links to screen shots if possible.
![image](https://cloud.githubusercontent.com/assets/1132431/8249262/189ccf80-1671-11e5-8c70-9dfd970d7c1d.png)

**Comment by QuincyLarson** [comment]
Thanks for spotting this! I've fixed this and will push the fix soon.

**Comment by Arthaey** [comment]
I'm seeing this error too. Has the fix been pushed yet?

**Comment by benmcmahon100** [comment]
It's most likely pushed but it's definitely not deployed right now

**Comment by mel1849** [comment]
This still seems to be an issue.

**Comment by daksh844** [comment]
Hi Quincy,

I'm still facing this issue, below is the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/8793646/8902582/9a2cea5a-346f-11e5-8978-c760323169e1.png)

**Comment by YannyRamz** [comment]
I think it should just be "cat photo URL", not the actual url

-. Y.Ramírez
     yanny.ramz@gmail.com
