### ISSUE TITLE
Compiler Not Responding to Code Change. Same output no matter the code

### ISSUE THREAD

**Issue by KindaIntellectual** [freeCodeCamp/freeCodeCamp#9936]
#### Challenge Name

https://www.freecodecamp.com/challenges/record-collection
#### Issue Description

The compiler does not seem to be running the provided code. I've tried different solutions, as well as running the code as is. Clicking run tests return the same two results. The first click produces the collection minus the 5439 object at the end, the next click brings up the entire collection with no changes.
#### Browser Information

- Browser Name, Version: Firefox 47.0.1
- Operating System: Windows 7 Home Premium
- Mobile, Desktop, or Tablet: Desktop
#### Your Code

example code

``` js

// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {


  return collection[id];
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");
```
#### Screenshot

![fcc1](https://cloud.githubusercontent.com/assets/7944583/17218417/ac2334e6-54b5-11e6-94a5-f1442b7eeeb4.png)
![fcc2](https://cloud.githubusercontent.com/assets/7944583/17218416/ac1d8b40-54b5-11e6-84a4-e173a35df6c7.png)

**Comment by KindaIntellectual** [comment]
So I wrote my code int eh console, and just for kicks added to FCC and ran the tests. The code passes but it doesn't actually update the code (at least not according to the FCC console) and gives the same results as above; with the exception of the test case at the bottom, it seems to update on the second and subsequent 'Run test' clicks. Code + screen shot below.

```js
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": []
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  var collectionLength = collection.length;
    if (prop !== "tracks" && value !== ""){
      collection[id][prop] = value;
    }
    if (prop === "tracks"){
      if (!collection[id].hasOwnProperty(prop)){
        collection[id].tracks = [];
      }
      collection[id].tracks.push(value);
    }
    if (!value){
      delete collection[id][prop];
    }
  
  return collection;
}
// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");

```
Screenshots:
![fcc1](https://cloud.githubusercontent.com/assets/7944583/17220739/928309ea-54be-11e6-99f1-dd0eace13451.png)
![fcc2](https://cloud.githubusercontent.com/assets/7944583/17220740/92891dbc-54be-11e6-87ea-565749f487cd.png)

**Comment by erictleung** [comment]
@KindaIntellectual thanks for the issue. I can confirm that the console on the page will hide the last entry for `5439`. The entry does exist after the first click. You just have to click on that area where it should be and it will appear. 

@FreeCodeCamp/issue-moderators does anyone know why this is happening? To reproduce, reload the challenge page https://www.freecodecamp.com/challenges/record-collection so that it shows

```js
/**
  * Your output will go here.
  * Any console.log() -type
  * statements will appear in
  * your browser's DevTools
  * JavaScript console as well.
  */
```

in the console. Then press "Run tests". The last entry for `5439` should be missing but then if you click on the area where it should be, it will appear.

**Comment by oalhait** [comment]
Hey @erictleung, I ran this on my Mac w/ Google Chrome, and the 5439 entry is showing without needing a click on it. I'm suspecting maybe this could be a windows-only issue?

**Comment by BerkeleyTrue** [comment]
@erictleung I believe this is a codemirror bug that was fixed in the editor a while ago. I'm sure if you search the issue's you can find the past solution

**Comment by KindaIntellectual** [comment]
Thanks @erictleung for looking into this as well as confirming it. I've never submitted an issue before and was just hoping this wasn't human error :)

**Comment by 190898** [comment]
Thanks everyone  ! I was having the same issue  !

**Comment by dwd2010** [comment]
@explorervd, if you got stuck with challenge, you could go to the [HelpJavaScript chat room](https://gitter.im/FreeCodeCamp/HelpJavaScript) for getting challenge related help.

Happy Coding!

**Comment by QuincyLarson** [comment]
@explorervd @KindaIntellectual are either of you still experiencing this issue? What about when you're using beta.freecodecamp.com?

**Comment by MaestroRich** [comment]
I am having the same problem..
